services:
  php71:
    build:
      context: docker/php71
      target: base
    volumes:
      - ./:/app
      - ./vendor-php71:/app/vendor

  php71debug:
    build:
      context: docker/php71
      target: debug
    volumes:
      - ./:/app
      - ./docker/php71:/usr/local/etc/php
      - ./vendor-php71:/app/vendor

  php71composer:
    build:
      context: docker/php71
      target: composer
    volumes:
      - ./:/app
      - ./vendor-php71:/app/vendor

  php72:
    build:
      context: docker/php72
      target: base
    volumes:
      - ./:/app
      - ./vendor-php72:/app/vendor

  php72debug:
    build:
      context: docker/php72
      target: debug
    volumes:
      - ./:/app
      - ./docker/php72:/usr/local/etc/php
      - ./vendor-php72:/app/vendor

  php72composer:
    build:
      context: docker/php72
      target: composer
    volumes:
      - ./:/app
      - ./vendor-php72:/app/vendor

  php73:
    build:
      context: docker/php73
      target: base
    volumes:
      - ./:/app
      - ./vendor-php73:/app/vendor

  php73debug:
    build:
      context: docker/php73
      target: debug
    volumes:
      - ./:/app
      - ./docker/php73:/usr/local/etc/php
      - ./vendor-php73:/app/vendor

  php73composer:
    build:
      context: docker/php73
      target: composer
    volumes:
      - ./:/app
      - ./vendor-php73:/app/vendor

  php74:
    build:
      context: docker/php74
      target: base
    volumes:
      - ./:/app
      - ./vendor-php74:/app/vendor

  php74debug:
    build:
      context: docker/php74
      target: debug
    volumes:
      - ./:/app
      - ./docker/php74:/usr/local/etc/php
      - ./vendor-php74:/app/vendor

  php74composer:
    build:
      context: docker/php74
      target: composer
    volumes:
      - ./:/app
      - ./vendor-php74:/app/vendor

  php80:
    build:
      context: docker/php80
      target: base
    volumes:
      - ./:/app
      - ./vendor-php80:/app/vendor

  php80debug:
    build:
      context: docker/php80
      target: debug
    volumes:
      - ./:/app
      - ./docker/php80:/usr/local/etc/php
      - ./vendor-php80:/app/vendor

  php80composer:
    build:
      context: docker/php80
      target: composer
    volumes:
      - ./:/app
      - ./vendor-php80:/app/vendor

  php81:
    build:
      context: docker/php81
      target: base
    volumes:
      - ./:/app
      - ./vendor-php81:/app/vendor

  php81debug:
    build:
      context: docker/php81
      target: debug
    volumes:
      - ./:/app
      - ./docker/php81:/usr/local/etc/php
      - ./vendor-php81:/app/vendor

  php81composer:
    build:
      context: docker/php81
      target: composer
    volumes:
      - ./:/app
      - ./vendor-php81:/app/vendor

  php82:
    build:
      context: docker/php82
      target: base
    volumes:
      - ./:/app
      - ./vendor-php82:/app/vendor

  php82debug:
    build:
      context: docker/php82
      target: debug
    volumes:
      - ./:/app
      - ./docker/php82:/usr/local/etc/php
      - ./vendor-php82:/app/vendor

  php82composer:
    build:
      context: docker/php82
      target: composer
    volumes:
      - ./:/app
      - ./vendor-php82:/app/vendor

  php83:
    build:
      context: docker/php83
      target: base
    volumes:
      - ./:/app
      - ./vendor-php83:/app/vendor

  php83debug:
    build:
      context: docker/php83
      target: debug
    volumes:
      - ./:/app
      - ./docker/php82:/usr/local/etc/php
      - ./vendor-php83:/app/vendor

  php83composer:
    build:
      context: docker/php83
      target: composer
    volumes:
      - ./:/app
      - ./vendor-php83:/app/vendor

  php84:
    build:
      context: docker/php84
      target: base
    volumes:
      - ./:/app
      - ./vendor-php84:/app/vendor

  php84debug:
    build:
      context: docker/php84
      target: debug
    volumes:
      - ./:/app
      - ./docker/php82:/usr/local/etc/php
      - ./vendor-php84:/app/vendor

  php84composer:
    build:
      context: docker/php84
      target: composer
    volumes:
      - ./:/app
      - ./vendor-php84:/app/vendor

networks:
  default:
    driver: bridge
    labels:
      auto-remove: "true"