name: tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:20.10.7
        options: --privileged

    strategy:
      matrix:
        php-version: [84, 83, 82, 81, 80, 74, 73, 72, 71]

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies for PHP${{ matrix.php-version }}
        run: |
          docker compose run --rm php${{ matrix.php-version }}composer composer update --no-cache

      - name: Run PHPUnit tests for PHP${{ matrix.php-version }}
        run: |
          docker compose run --rm php${{ matrix.php-version }} vendor/bin/phpunit --configuration phpunit${{ matrix.php-version }}.xml